### ISSUE TITLE
how to fix

### ISSUE THREAD

**Issue by alonalibarmn** [SKATEB0ARD/licensing-system#1]
![image](https://user-images.githubusercontent.com/71559074/97781008-26cb5600-1b91-11eb-9685-b1a271cba4cb.png)

**Comment by SKATEB0ARD** [comment]
OH i forgot composer 2.0 doesnt allow dashes try now

**Comment by SKATEB0ARD** [comment]
did it get fixed ?

**Comment by alonalibarmn** [comment]
yes ty bro
you are the best!!

**Comment by alonalibarmn** [comment]
whare is licenses.sql 
and config

**Comment by SKATEB0ARD** [comment]
oh i forgot to include those if you give me about a hour to finish some school work i can push those real quick.

**Comment by SKATEB0ARD** [comment]
there you go dude 👍

**Comment by SKATEB0ARD** [comment]
forgot to upload them
